#
# Test build action
#

name: Build and test

on:
  push:
    branches: [ 'main', 'gfs/TestGlobs' ]
  pull_request:
    branches: [ 'main' ]
  workflow_dispatch:

jobs:

  # Check that container image can be built
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

      # Allow upload of events into GitHub Security tab
      security-events: write
    steps:

    - uses: actions/checkout@v4

    # Check that dockerfile can be built
    - name: Build action image
      run: docker build . --file Dockerfile

    # Can the action run successful against the repo
    - name: Self test action
      uses: ./
      with:
        ignore-globs: '**/one/*.cs'
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        # Artifact name
        name: devskim-results.sarif # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: devskim-results.sarif
        # The desired behavior if no files are found using the provided path.
        if-no-files-found: error # optional, default is warn
        # Duration after which artifact will expire in days. 0 means using default retention.
        retention-days: 1 # optional
    - name: SARIF Multitool
      uses: microsoft/sarif-actions@v0.1
      with:
        # Command to be sent to SARIF Multitool
        command: validate devskim-results.sarif # optional, default is version
    # Make sure results exist and can by uploaded
    - name: Upload results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: devskim-results.sarif
